spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://127.0.0.1:8060/auth/realms/RSOCKET
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: gateway
            client-secret: 059fa1a6-b94f-42a1-81c8-210acfe6f299
            scope: openid
